default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_2:
    has_position_limits: true
    min_position: -2.2689
    max_position: 2.2689
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_4:
    has_position_limits: true
    min_position: -2.618
    max_position: 2.618
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_6:
    has_position_limits: true
    min_position: -2.0944
    max_position: 2.0944
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: true
    max_acceleration: 8.6
  joint_7:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: true
    max_acceleration: 8.6
  finger_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_inner_knuckle_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_inner_finger_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_outer_knuckle_joint:
    has_position_limits: true
    min_position: -0.85
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_inner_knuckle_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_inner_finger_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
